// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ChinasMr/kaka/internal/conf"
	"github.com/ChinasMr/kaka/pkg/app"
	"github.com/ChinasMr/kaka/pkg/log"
)

// Injectors from wire.go:

func wireApp(server *conf.Server, logger log.Logger) (*app.App, func(), error) {
	appApp := newApp(logger)
	return appApp, func() {
	}, nil
}
