// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ChinasMr/kaka/internal/biz"
	"github.com/ChinasMr/kaka/internal/conf"
	"github.com/ChinasMr/kaka/internal/data"
	"github.com/ChinasMr/kaka/internal/server"
	"github.com/ChinasMr/kaka/internal/service"
	"github.com/ChinasMr/kaka/pkg/application"
	"github.com/ChinasMr/kaka/pkg/log"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, logger log.Logger) (*application.App, func(), error) {
	roomRepo := data.NewRoomRepo(logger)
	kakaUseCase := biz.NewKakaUseCase(logger, roomRepo)
	kakaService := service.NewKakaService(logger, kakaUseCase)
	grpcServer := server.NewGRPCServer(confServer, kakaService)
	rtspServer := server.NewRTSPServer(confServer, kakaService, logger)
	app := newApp(logger, grpcServer, rtspServer)
	return app, func() {
	}, nil
}
