// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.4.0
// - protoc             v3.20.1
// source: kaka/v1/kaka.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKakaDebug = "/api.kaka.v1.Kaka/Debug"

type KakaHTTPServer interface {
	Debug(context.Context, *DebugRequest) (*DebugReply, error)
}

func RegisterKakaHTTPServer(s *http.Server, srv KakaHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/debug", _Kaka_Debug0_HTTP_Handler(srv))
}

func _Kaka_Debug0_HTTP_Handler(srv KakaHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DebugRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKakaDebug)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Debug(ctx, req.(*DebugRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DebugReply)
		return ctx.Result(200, reply)
	}
}

type KakaHTTPClient interface {
	Debug(ctx context.Context, req *DebugRequest, opts ...http.CallOption) (rsp *DebugReply, err error)
}

type KakaHTTPClientImpl struct {
	cc *http.Client
}

func NewKakaHTTPClient(client *http.Client) KakaHTTPClient {
	return &KakaHTTPClientImpl{client}
}

func (c *KakaHTTPClientImpl) Debug(ctx context.Context, in *DebugRequest, opts ...http.CallOption) (*DebugReply, error) {
	var out DebugReply
	pattern := "/api/v1/debug"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKakaDebug))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
